### ISSUE TITLE
Game playable after closing the "Winning" Window

### ISSUE THREAD

**Issue by DanielKng** [DanielKng/Tic-Tac-Toe#2]
If you won the game and put the Animation-Window aside, you are still able to click the buttons and win again, and again, and again.

[Click here for a demonstration](https://i.gyazo.com/8edfa3c0d5be80b5b88827f9cea134f1.gif)

**Comment by Ischke** [comment]
The players name is shown in the winning screen, [as you can see here](https://gyazo.com/5fd2d26bc591ed96773398188973ebfc).
