### ISSUE TITLE
Everyone is winning-bug

### ISSUE THREAD

**Issue by Ischke** [DanielKng/Tic-Tac-Toe#3]
The players name is shown in the winning screen after you put the window aside or close it and click on an empty field.
[Here](https://gyazo.com/5fd2d26bc591ed96773398188973ebfc) is an example:

The actual winner was X, so 'X wins! Congratulations!' is correct. After I closed the window and clicked again it says 'O wins! Congratulations!'.

**Comment by DanielKng** [comment]
To clarify that: Once you won, you are able to play the Game like normal?

**Comment by Ischke** [comment]
After someone won the first time, you are just able to fill all the fields and 'the bug' shows itself. But you are able to click on 'New Game', so you can easily play a new round.

**Comment by DanielKng** [comment]
Ah, okay. Yeah, thats what i thought. You won and can still press the Buttons. Thanks, will take a look!
