### ISSUE TITLE
Multiple winning screen windows

### ISSUE THREAD

**Issue by Ischke** [DanielKng/Tic-Tac-Toe#4]
I played a little with the ideas I had in mind and found this one:

![Multiple winning windows](http://img.prntscr.com/img?url=http://i.imgur.com/WTUY6a3.png)

After you won, you may aren't able to fill the fields anymore (thanks for fixing this one @DanielKng), but you are able to make a new game and create multiple screens, as shown above.

Idea for fixing: force the winning window to close after you pressed 'New Game'.

**Comment by Nico-Br** [comment]
Working on it! @Ischke 

Pretty weird situation, since the Window doesnt get closed by `this.Hide();` or `Winscreen.Close()`.

**Comment by DanielKng** [comment]
I'll just leave this here, found on our Stackoverflow:
You need a field in our Game.cs

private Winscreen winscreen = null;

When you're presenting the window to the user, assign the instance to this variable:

this.winscreen = new Winscreen();
this.winscreen.Show();    // or whatever you're doing currently

This way, you are able to store a reference to the window that is actually shown on the screen. In your current solution, you are creating a new instance each time - each of them having nothing to do with the previously opened window.

Then when starting a new game you can close the popup:

private void New_Game_Click(object sender, EventArgs e)
{
    if (this.winscreen != null)
    {
        this.winscreen.CloseWinscreen();
        this.winscreen = null;
    }

// ...
}

**Comment by DanielKng** [comment]
Since @Nico-Br couldn't get this to work I did the fix. I also found a better solution for this. See the commit for more details!
