### ISSUE TITLE
Instant win and broke

### ISSUE THREAD

**Issue by Ischke** [DanielKng/Tic-Tac-Toe#5]
When you create a new game with playernames and set only one name as shown below, the player 1 always wins when he just klick in one field.
The empty field in 'Player 1' gets set as X, the one in 'Player 2' as O.

![instant win](https://i.gyazo.com/fc6b63f271726fb0390e085d07a282f5.gif)

EDIT:

For some reason I broke the game, but I can't really explain how I did it.

![broke](https://media.giphy.com/media/xT4uQ6CgpS9pryry3m/giphy.gif)

**Comment by Nico-Br** [comment]
If there is only one Player, only one player is able to win, so this is more a "feature" than a bug. Will fix it anyway, thanks!
