### ISSUE TITLE
Player Names Validation

### ISSUE THREAD

**Issue by py444** [DanielKng/Tic-Tac-Toe#6]
Great Work Guys 
- if the player enter a very long name , the name will go offscreen .. maybe a 10 characters name will be valid ! 
- the play shouldn't be able to put spaces in their name 
, if you try to put a spaces in player 1 name and no name in the player 2 name . you will win from the first turn ! 
- if you start the name with a " " , in place of "O" or "X" , it will be nothing .. i think it's because it take first character from the name .

**Comment by DanielKng** [comment]
Thanks! I'm on it. 
So you can't put a space before a Name, can't use just a Space (`" "`)  or use special characters in your Name. 
To be honest, I didn't thought someone would do this ;)
